name: Check phenopacket-store for a new release
on:
  schedule:
    - cron: "0 0 * * 5" # Run weekly on Friday at 00:00 UTC
  workflow_dispatch:
    inputs:  
      dry_run:
        description: 'Skip follow-up steps like Zenodo uploads'
        required: false
        default: 'true'

jobs:
  check_release:
    name: Check for new phenopacket-store release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    outputs:
      latest_store_tag: ${{ steps.check.outputs.latest_store_tag }}
      latest_hpo_tag: ${{ steps.check.outputs.latest_hpo_tag }}
      new_release: ${{ steps.check.outputs.new_release }}


    steps:
      - uses: actions/checkout@v4
      - name: Set up Python for to run ppkt-store checker
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use latest stable version

      - name: Install python dependencies
        run: pip install requests

      - name: Run release checker
        id: check
        env:
            GH_TOKEN: ${{ secrets.GH_PAT_LEO }}
        run: python scripts/check_ppktstore_version.py

  follow_up_prompt_creation:
      needs: check_release
      if: needs.check_release.outputs.new_release == 'true' && github.event.inputs.dry_run != 'true'      
      uses: ./.github/workflows/create_prompts_and_upload.yml
      with:
        LATEST_STORE: ${{ needs.check_release.outputs.latest_store_tag }}
        LATEST_HPO: ${{ needs.check_release.outputs.latest_hpo_tag }}
      secrets:
        ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_ACCESS_TOKEN }}
        ZENODO_DEPOSITION_ID: ${{ secrets.ZENODO_DEPOSITION_ID }}
